### ISSUE TITLE
favicon not showing when deployed on github

### ISSUE THREAD

**Issue by evanthebouncy** [jitinnair1/gradfolio#22]
this is probably a long shot, but I couldn't get my own favicons to work. they work locally
<img width="108" alt="Screen Shot 2022-10-10 at 11 53 15 PM" src="https://user-images.githubusercontent.com/1041553/195016897-9aa649d8-a862-4d6a-8695-1d6461852903.png">

but once deployed on github they dont
<img width="125" alt="Screen Shot 2022-10-10 at 11 53 42 PM" src="https://user-images.githubusercontent.com/1041553/195016990-22facb2b-a503-49b8-9063-d8ae49c19301.png">

would you have any hints as to why that is? the project is this one:
https://github.com/evanthebouncy/evanthebouncy.github.io

it is rendered at this url:
https://evanthebouncy.github.io/

thanks!!

btw gradfolio is the cleanest academic template I've found after browsing through all of them, the simplicity is the best!

**Comment by jitinnair1** [comment]
Hi @evanthebouncy! Thank you for the kind words, I'm glad you liked the template.

I just checked and it looks like the favicon is now visible on your website:

![favicon_issue](https://user-images.githubusercontent.com/2485715/195051845-8d85595d-5735-4b08-a3d1-5a5cb8319ba1.png)

It was likely due to caching issues. Please re-open the issue if needed.
