### ISSUE TITLE
Error while execution

### ISSUE THREAD

**Issue by VishalPallagani** [jitinnair1/gradfolio#7]
I really like the template and wish to use it as my portfolio template. As mentioned in the previous closed issue, I have removed the plugin jekyll-target-blank. I still get the following error

<img width="570" alt="Screen Shot 2021-06-13 at 9 30 18 AM" src="https://user-images.githubusercontent.com/22969140/121809222-f9b44b00-cc29-11eb-9c69-fb7c608edb52.png">

Any help would be appreciated.

**Comment by jitinnair1** [comment]
Can you try running `jekyll serve --incremental --trace` after making the following changes:
- [Modify the `url` in `_config.yml`](https://github.com/jitinnair1/gradfolio/blob/f70697383edc84fa1ad19d46dde8bb8858a8663f/_config.yml#L7) field by adding a `""`
- Add the  `jekyll-target-blank` back under plugins 

```
url: ""
```

My guess is that `jekyll-target-blank` is added as a dependency somewhere and as mentioned in the earlier issue, the error is because `jekyll-target-blank` was getting a blank input. I could not recreate the error on my machine so it would be helpful if you can test this and let me know.

**Comment by VishalPallagani** [comment]
I have made the changes as mentioned.
<img width="374" alt="Screen Shot 2021-06-14 at 6 49 07 AM" src="https://user-images.githubusercontent.com/22969140/121881098-c8e11e00-ccdc-11eb-894b-dd942f84b027.png">
<img width="701" alt="Screen Shot 2021-06-14 at 6 48 55 AM" src="https://user-images.githubusercontent.com/22969140/121881108-cbdc0e80-ccdc-11eb-8dbc-b0ce1fcd22cc.png">

I got the error of email-protect (I added the email as well without leaving it blank)

**Comment by jitinnair1** [comment]
Okay, I noticed the error message clearly now. I think running `gem install jekyll-email-protect` should fix it.

**Comment by VishalPallagani** [comment]
Thank you so much, I thought i had all the gems installed. My bad.

**Comment by jitinnair1** [comment]
Glad this got sorted :)
